### ISSUE TITLE
qlementine-icons can't follow the qlementine's "dark" or "light" style

### ISSUE THREAD

**Issue by programClown** [oclero/qlementine-icons#3]

**Comment by programClown** [comment]
solved it!

**Comment by nlogozzo** [comment]
@programClown How did you fix it? I am experiencing the same thing:

![Image](https://github.com/user-attachments/assets/e85a407a-456a-4438-9c40-ac3c20448838)
![Image](https://github.com/user-attachments/assets/7e0ccc99-31c4-40d9-85a4-dbded7d4b8d8)

**Comment by nlogozzo** [comment]
Got it, had to add `m_style->setAutoIconColor(oclero::qlementine::AutoIconColor::TextColor);`

**Comment by oclero** [comment]
You have to enable the automatic icon coloring 👍
